dual_arm_panda_moveit_config:
  ubuntu:
  - ros-humble-dual-arm-panda-moveit-config
moveit:
  ubuntu:
  - ros-humble-moveit
moveit_common:
  ubuntu:
  - ros-humble-moveit-common
moveit_configs_utils:
  ubuntu:
  - ros-humble-moveit-configs-utils
moveit_msgs:
  ubuntu:
  - ros-humble-moveit-msgs
moveit_planners:
  ubuntu:
  - ros-humble-moveit-planners
moveit_plugins:
  ubuntu:
  - ros-humble-moveit-plugins
moveit_resources:
  ubuntu:
  - ros-humble-moveit-resources
moveit_resources_fanuc_description:
  ubuntu:
  - ros-humble-moveit-resources-fanuc-description
moveit_resources_fanuc_moveit_config:
  ubuntu:
  - ros-humble-moveit-resources-fanuc-moveit-config
moveit_resources_panda_description:
  ubuntu:
  - ros-humble-moveit-resources-panda-description
moveit_resources_panda_moveit_config:
  ubuntu:
  - ros-humble-moveit-resources-panda-moveit-config
moveit_resources_pr2_description:
  ubuntu:
  - ros-humble-moveit-resources-pr2-description
moveit_core:
  ubuntu:
  - ros-humble-moveit-core
chomp_motion_planner:
  ubuntu:
  - ros-humble-chomp-motion-planner
moveit_chomp_optimizer_adapter:
  ubuntu:
  - ros-humble-moveit-chomp-optimizer-adapter
moveit_planners_chomp:
  ubuntu:
  - ros-humble-moveit-planners-chomp
moveit_planners_stomp:
  ubuntu:
  - ros-humble-moveit-planners-stomp
moveit_resources_prbt_ikfast_manipulator_plugin:
  ubuntu:
  - ros-humble-moveit-resources-prbt-ikfast-manipulator-plugin
moveit_resources_prbt_moveit_config:
  ubuntu:
  - ros-humble-moveit-resources-prbt-moveit-config
moveit_resources_prbt_pg70_support:
  ubuntu:
  - ros-humble-moveit-resources-prbt-pg70-support
moveit_resources_prbt_support:
  ubuntu:
  - ros-humble-moveit-resources-prbt-support
moveit_ros:
  ubuntu:
  - ros-humble-moveit-ros
moveit_ros_occupancy_map_monitor:
  ubuntu:
  - ros-humble-moveit-ros-occupancy-map-monitor
moveit_ros_planning:
  ubuntu:
  - ros-humble-moveit-ros-planning
moveit_kinematics:
  ubuntu:
  - ros-humble-moveit-kinematics
moveit_planners_ompl:
  ubuntu:
  - ros-humble-moveit-planners-ompl
moveit_ros_move_group:
  ubuntu:
  - ros-humble-moveit-ros-move-group
moveit_ros_perception:
  ubuntu:
  - ros-humble-moveit-ros-perception
moveit_ros_robot_interaction:
  ubuntu:
  - ros-humble-moveit-ros-robot-interaction
moveit_ros_warehouse:
  ubuntu:
  - ros-humble-moveit-ros-warehouse
moveit_ros_benchmarks:
  ubuntu:
  - ros-humble-moveit-ros-benchmarks
moveit_runtime:
  ubuntu:
  - ros-humble-moveit-runtime
moveit_simple_controller_manager:
  ubuntu:
  - ros-humble-moveit-simple-controller-manager
moveit_ros_control_interface:
  ubuntu:
  - ros-humble-moveit-ros-control-interface
moveit_ros_planning_interface:
  ubuntu:
  - ros-humble-moveit-ros-planning-interface
moveit_hybrid_planning:
  ubuntu:
  - ros-humble-moveit-hybrid-planning
moveit_py:
  ubuntu:
  - ros-humble-moveit-py
moveit_ros_visualization:
  ubuntu:
  - ros-humble-moveit-ros-visualization
moveit_servo:
  ubuntu:
  - ros-humble-moveit-servo
moveit_setup_framework:
  ubuntu:
  - ros-humble-moveit-setup-framework
moveit_setup_app_plugins:
  ubuntu:
  - ros-humble-moveit-setup-app-plugins
moveit_setup_controllers:
  ubuntu:
  - ros-humble-moveit-setup-controllers
moveit_setup_core_plugins:
  ubuntu:
  - ros-humble-moveit-setup-core-plugins
moveit_setup_srdf_plugins:
  ubuntu:
  - ros-humble-moveit-setup-srdf-plugins
moveit_setup_assistant:
  ubuntu:
  - ros-humble-moveit-setup-assistant
moveit_task_constructor_msgs:
  ubuntu:
  - ros-humble-moveit-task-constructor-msgs
pilz_industrial_motion_planner_testutils:
  ubuntu:
  - ros-humble-pilz-industrial-motion-planner-testutils
pilz_industrial_motion_planner:
  ubuntu:
  - ros-humble-pilz-industrial-motion-planner
rosparam_shortcuts:
  ubuntu:
  - ros-humble-rosparam-shortcuts
rviz_marker_tools:
  ubuntu:
  - ros-humble-rviz-marker-tools
moveit_task_constructor_core:
  ubuntu:
  - ros-humble-moveit-task-constructor-core
moveit_task_constructor_capabilities:
  ubuntu:
  - ros-humble-moveit-task-constructor-capabilities
moveit_task_constructor_demo:
  ubuntu:
  - ros-humble-moveit-task-constructor-demo
moveit_task_constructor_visualization:
  ubuntu:
  - ros-humble-moveit-task-constructor-visualization
rviz_visual_tools:
  ubuntu:
  - ros-humble-rviz-visual-tools
moveit_visual_tools:
  ubuntu:
  - ros-humble-moveit-visual-tools
