name: build

on:
  workflow_dispatch:
  schedule:
    - cron: '17 1 * * *'

jobs:
  build_job:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        ros_distro: [humble, rolling]
    name: build_${{ matrix.ros_distro }}
    runs-on: ubuntu-22.04
    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: jammy
          ROS_DISTRO: ${{ matrix.ros_distro }}
          REPOS_FILE: https://raw.githubusercontent.com/ros-planning/moveit2_tutorials/main/moveit2_tutorials.repos
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true


  iron:
    strategy:
      fail-fast: false
      max-parallel: 4
    name: build_iron
    runs-on: ubuntu-22.04
    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: jammy
          ROS_DISTRO: iron
          REPOS_FILE: https://raw.githubusercontent.com/ros-planning/moveit2_tutorials/main/moveit2_tutorials.repos
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          SBUILD_CONF: $extra_repositories = ["deb http://packages.ros.org/ros2-testing/ubuntu jammy main"];
